### ISSUE TITLE
nebula-setup: nginx : installation failed

### ISSUE THREAD

**Issue by Abdelkrim** [nebulabroadcast/nebula-setup#8] opened 2021-03-28 18:48 UTC
to whom it may concern,

# use case

1. I started an installation of nebula from a brand new virtual machine on Ubuntu: 
    1. `multipass launch --name nebula` - Ubuntu 20.04.2 LTS
    2. `multipass shell nebula`
    3. `git clone git@github.com:nebulabroadcast/nebula-setup.git`
    4. `sudo apt update`
    5. `sudo apt install python3-pip`
2. I followed the instructions available on [https://github.com/nebulabroadcast/nebula-setup](https://github.com/nebulabroadcast/nebula-setup)
3. Install the prerequisites
    1. `sudo ./prerequisite.sh`
 4. Install nginx
    1. `curl -s https://raw.githubusercontent.com/immstudios/installers/master/install.nginx.sh | sudo bash` 

# the error happening at the 'post-install configuration'

> make[1]: Leaving directory '/tmp/nginx-1.19.8'
> Running post-install configuration...
> cp: cannot stat 'nginx/nginx.conf': No such file or directory
> 
> Installation failed

# Question

do you know why do I receive such error?

Thank you in advance for your help

**Comment by martastain** [comment] 2021-03-29 12:15
Duplicate of https://github.com/immstudios/nebula-setup/issues/1 ... Installer is now updated so the configuration files are embedded into the script.

**Closed by martastain** 2021-03-29 12:15 UTC
